/**
 * Traductions pré-générées pour les articles du catalogue.
 * Traductions fidèles et complètes des descriptions françaises originales.
 * Source primaire — appliquées systématiquement au démarrage et via l'admin.
 */
const CATALOGUE_TRANSLATIONS: Record<string, { name_en: string; name_es: string; desc_en: string; desc_es: string }> = {
  "Monopalme à Extension sirène": {
    "name_en": "Mermaid Extension Monofin",
    "name_es": "Monoaleta de extensión sirena",
    "desc_en": "Our monofins have been studied for 10 years with the help of an aeronautical engineer in order to achieve perfect functionality! Unlike monofins on the market, which are not at all designed for mermaid swimming or to be integrated into silicone, ours are fully designed for this purpose.\n\nMade from polycarbonate, a material commonly used in aeronautics, they offer lightness, strength and durability. Their shape has been designed to provide great manoeuvrability during aquatic figures while also offering great speed, just like a real professional diving monofin.\n\nThey are also large — 75 to 80 cm wide by 75 cm long — for all our different shapes (Siren, Ariel, Lagoon, etc.).\n\nThe extension between the tip of the slippers and the silicone is approximately 15 cm — this unique feature in the world provides striking realism!\n\nThere is no water infiltration inside! The polycarbonate monofin is completely integrated into a special silicone that adheres perfectly to it. It is this manufacturing technique that gives you a perfectly functional swim!\n\nOur slippers are very comfortable and cause no injuries thanks to their soles! You can wear them for several hours without any risk.\n\nThey can be fitted with a zip, allowing you to easily attach your fabric or silicone scales. This system also makes it easy to change scale colours quickly and easily.\n\nWeight of the monofin: approximately 2 kg.\n\nCreation time: approximately 3 months.\n\nOn its own, it will be fitted with silicone scales up to the tips of the slippers.\n\nStarting from 1,350 euros\n\n \n\nPrice of additional options:\n\n- Zip (to attach your scales): 80 euros.\n\n- Additional colour: 20 euros per colour.\n\n- Chameleon colour (colour that changes shade depending on position): 75 euros\n\n- Holographic colour (rainbow reflections): 100 euros.",
    "desc_es": "¡Nuestras monoaletas han sido estudiadas durante 10 años con la ayuda de un ingeniero aeronáutico para lograr una funcionalidad perfecta! A diferencia de las monoaletas del mercado, que no están diseñadas para nadar como sirena ni para ser integradas en silicona, las nuestras están totalmente diseñadas para ello.\n\nFabricadas en policarbonato, un material de uso habitual en aeronáutica, ofrecen ligereza, solidez y durabilidad. Su forma ha sido concebida para ofrecer una gran maniobrabilidad durante las figuras acuáticas, al mismo tiempo que proporciona gran velocidad, como con una auténtica monoaleta de buceo profesional.\n\nSon también grandes — de 75 a 80 cm de ancho por 75 cm de largo — para todas nuestras diferentes formas (Siren, Ariel, Lagoon, etc.).\n\nEl alargamiento entre la punta de los botines y la silicona es de aproximadamente 15 cm — ¡esta particularidad única en el mundo ofrece un realismo impresionante!\n\n¡No hay infiltración de agua en el interior! La monoaleta de policarbonato está completamente integrada en una silicona especial que se adhiere perfectamente a ella. ¡Es esta técnica de fabricación la que le ofrece una natación perfectamente funcional!\n\n¡Nuestros botines son muy cómodos y no causan ninguna lesión gracias a sus suelas! Podrá llevarlos durante varias horas sin riesgo.\n\nPueden equiparse con una cremallera, lo que permite fijar fácilmente las escamas de tela o silicona. Este sistema también permite cambiar el color de las escamas de forma rápida y sencilla.\n\nPeso de la monoaleta: aproximadamente 2 kg.\n\nPlazo de creación: aproximadamente 3 meses.\n\nSola, estará equipada con escamas de silicona hasta la punta de los botines.\n\nA partir de 1.350 euros\n\n \n\nPrecio de los detalles adicionales:\n\n- Cremallera (para sujetar las escamas): 80 euros.\n\n- Color adicional: 20 euros por color.\n\n- Color camaleón (color que cambia de tonalidad según la posición): 75 euros\n\n- Color holográfico (reflejos arcoíris): 100 euros."
  },
  "Monopalme sirène": {
    "name_en": "Mermaid Monofin",
    "name_es": "Monoaleta sirena",
    "desc_en": "Our mermaid monofins have been studied for 10 years with the help of an aeronautical engineer in order to achieve perfect functionality! Unlike monofins on the market, which are not at all designed for mermaid swimming or to be integrated into silicone, ours are fully designed for this purpose.\n\nMade from polycarbonate, a material commonly used in aeronautics, they offer lightness, strength and durability. Their shape has been designed to provide great manoeuvrability during aquatic figures while also offering great speed, just like a real professional diving monofin.\n\nThey are also large — 75 to 80 cm wide by 75 cm long — for all our different shapes (Siren, Ariel, Lagoon, etc.).\n\nThere is no water infiltration inside! The polycarbonate monofin is completely integrated into a special silicone that adheres perfectly to it. It is this manufacturing technique that gives you a perfectly functional swim!\n\nOur slippers are very comfortable and cause no injuries thanks to their soles! You can wear them for several hours without any risk.\n\nAs an option you can add a zip, allowing you to easily attach your fabric or silicone scales. This system also makes it easy to change scale colours quickly and easily.\n\nAs an optional extra you can also add silicone scales covering the slippers.\n\nCreation time: approximately 2 months.\n\nOur mermaid monofins start from 890 euros.\n\nThis price is for a single-colour monofin (excluding chameleon and holographic effects).\n\nPrice of additional options:\n\n \n\n- Silicone scales on and around the slippers: 90 euros\n\n- Zip (to attach your scales): 50 euros.\n\n- Additional colour: 20 euros per colour.\n\n- Chameleon colour (colour that changes shade depending on position): 75 euros\n\n- Holographic colour (rainbow reflections): 100 euros.",
    "desc_es": "¡Nuestras monoaletas de sirena han sido estudiadas durante 10 años con la ayuda de un ingeniero aeronáutico para lograr una funcionalidad perfecta! A diferencia de las monoaletas del mercado, que no están diseñadas para nadar como sirena ni para ser integradas en silicona, las nuestras están totalmente diseñadas para ello.\n\nFabricadas en policarbonato, un material de uso habitual en aeronáutica, ofrecen ligereza, solidez y durabilidad. Su forma ha sido concebida para ofrecer una gran maniobrabilidad durante las figuras acuáticas, al mismo tiempo que proporciona gran velocidad, como con una auténtica monoaleta de buceo profesional.\n\nSon también grandes — de 75 a 80 cm de ancho por 75 cm de largo — para todas nuestras diferentes formas (Siren, Ariel, Lagoon, etc.).\n\n¡No hay infiltración de agua en el interior! La monoaleta de policarbonato está completamente integrada en una silicona especial que se adhiere perfectamente a ella. ¡Es esta técnica de fabricación la que le ofrece una natación perfectamente funcional!\n\n¡Nuestros botines son muy cómodos y no causan ninguna lesión gracias a sus suelas! Podrá llevarlos durante varias horas sin riesgo.\n\nComo opción puede añadir una cremallera, lo que permite fijar fácilmente las escamas de tela o silicona. Este sistema también permite cambiar el color de las escamas de forma rápida y sencilla.\n\nComo opción adicional también puede añadir escamas de silicona que cubran los botines.\n\nPlazo de creación: aproximadamente 2 meses.\n\nNuestras monoaletas de sirena tienen un precio a partir de 890 euros.\n\nEste precio corresponde a una monoaleta de un solo color (excluidos los efectos camaleón y holográfico).\n\nPrecio de los detalles adicionales:\n\n \n\n- Escamas de silicona sobre y alrededor de los botines: 90 euros\n\n- Cremallera (para sujetar las escamas): 50 euros.\n\n- Color adicional: 20 euros por color.\n\n- Color camaleón (color que cambia de tonalidad según la posición): 75 euros\n\n- Color holográfico (reflejos arcoíris): 100 euros."
  },
  "Queue de sirène silicone": {
    "name_en": "Silicone Mermaid Tail",
    "name_es": "Cola de sirena de silicona",
    "desc_en": "The \"classic silicone\" mermaid tails are made entirely of professional-grade silicone, non-toxic for skin or aquariums. Silicone is a soft, elastic material that provides a second-skin effect. It also offers protection from the cold, like a wetsuit. The monofin has been designed for fast and agile swimming — see all the monofin specifications in the \"monofin\" section. Weight: approximately 7 kg. Colours are applied beneath a layer of transparent silicone rather than airbrushed, which means the colour does not chip over time — the finish is perfect with repeated use and gives a unique iridescent effect. We also offer magical colours such as the chameleon effect (which changes shade depending on position) and holographic (rainbow effect). The creation time for this model is approximately 4 months from receipt of payment, though this depends on the number of orders in progress and material availability. A precise lead time will be provided with your free quote.\nThe technique used to apply silicone to the monofin is designed for strong adhesion to prevent any peeling — unlike industrial monofins where the silicone does not adhere.\n\n\nOur \"classic silicone\" fins start from 1,990 euros. This price is for a single-colour fin (excluding chameleon and holographic effects), without small fins or dorsal fins.\n\nPrice of additional options:\n\n- A pair of small lateral fins, front or back: 100 euros per pair.\n\n- Medium dorsal fin from knees to ankles: 150 euros\n\n- Large dorsal fin from hips to ankles: 200 euros\n\n- Additional colour: 50 euros per colour\n\n- Chameleon colour (colour that changes shade depending on position): 100 euros\n\n- Holographic colour (rainbow reflections): 200 euros",
    "desc_es": "Las colas de sirena \"clásico silicona\" están fabricadas íntegramente en silicona profesional, no tóxica para la piel ni para los acuarios. La silicona es un material suave y elástico que ofrece un efecto segunda piel. También proporciona protección contra el frío, como un traje de neopreno. La monoaleta ha sido diseñada para una natación rápida y ágil — consulte todas las características de la monoaleta en la sección \"monoaleta\". Peso: aproximadamente 7 kg. Los colores se aplican bajo una capa de silicona transparente en lugar de con aerógrafo, lo que evita que el color se descascare con el tiempo — el acabado es perfecto con el uso repetido y da un efecto iridiscente único. También ofrecemos colores mágicos como el efecto camaleón (que cambia de tonalidad según la posición) y holográfico (efecto arcoíris). El plazo de creación de este modelo es de aproximadamente 4 meses a partir de la recepción del pago, aunque esto depende del número de pedidos en curso y de la disponibilidad del material. Se le proporcionará un plazo preciso con su presupuesto gratuito.\nLa técnica de aplicación de la silicona sobre la monoaleta está diseñada para una fuerte adherencia y evitar cualquier despegue, a diferencia de las monoaletas industriales donde la silicona no adhiere.\n\n\nNuestras aletas \"clásico silicona\" tienen un precio a partir de 1.990 euros. Este precio corresponde a una aleta de un solo color (excluidos los efectos camaleón y holográfico), sin aletas pequeñas ni dorsal.\n\nPrecio de los detalles adicionales:\n\n- Un par de aletas laterales pequeñas, delanteras o traseras: 100 euros el par.\n\n- Aleta dorsal mediana de rodillas a tobillos: 150 euros\n\n- Aleta dorsal grande de caderas a tobillos: 200 euros\n\n- Color adicional: 50 euros por color\n\n- Color camaleón (color que cambia de tonalidad según la posición): 100 euros\n\n- Color holográfico (reflejos arcoíris): 200 euros"
  },
  "Queue de sirène silicone \"Pieds invisibles\"": {
    "name_en": "Silicone Mermaid Tail \"Invisible Feet\"",
    "name_es": "Cola de sirena de silicona \"Pies invisibles\"",
    "desc_en": "The \"Invisible Feet\" mermaid tails are made entirely of professional-grade silicone, non-toxic for skin or aquariums. Silicone is a soft, elastic material that provides a second-skin effect. It also offers protection from the cold, like a wetsuit.\nThe monofin is the same as for the \"classic silicone\" model, designed for fast and agile swimming — see all the monofin specifications in the \"monofin\" section.\n\nWeight: approximately 8 kg.\n\nColours are applied beneath a layer of transparent silicone rather than airbrushed, which means the colour does not chip over time — the finish is perfect with repeated use and gives a unique iridescent effect.\n\nWe also offer magical colours such as the chameleon effect (which changes shade depending on position) and the holographic effect (rainbow effect).\n\nThis model has a special feature: internal padding that completely conceals the shape of the foot for an even more realistic effect!\n\nThe creation time for this model is approximately 5 months from receipt of payment, though this depends on the number of orders in progress and material availability. A precise lead time will be provided with your free quote.\n\nOur \"silicone invisible feet\" fins start from 2,500 euros. This price is for a single-colour fin (excluding chameleon and holographic effects), without small fins or dorsal fins.\n\nPrice of additional options:\n\n- A pair of small lateral fins, front or back: 100 euros per pair.\n\n- Medium dorsal fin from knees to ankles: 150 euros\n\n- Large dorsal fin from hips to ankles: 200 euros\n\n- Additional colour: 50 euros per colour\n\n- Chameleon colour (colour that changes shade depending on position): 100 euros\n\n- Holographic colour (rainbow reflections): 200 euros",
    "desc_es": "Las colas de sirena \"Pies invisibles\" están fabricadas íntegramente en silicona profesional, no tóxica para la piel ni para los acuarios. La silicona es un material suave y elástico que ofrece un efecto segunda piel. También proporciona protección contra el frío, como un traje de neopreno.\nLa monoaleta es la misma que para el modelo \"clásico silicona\", diseñada para una natación rápida y ágil — consulte todas las características de la monoaleta en la sección \"monoaleta\".\n\nPeso: aproximadamente 8 kg.\n\nLos colores se aplican bajo una capa de silicona transparente en lugar de con aerógrafo, lo que evita que el color se descascare con el tiempo — el acabado es perfecto con el uso repetido y da un efecto iridiscente único.\n\nTambién ofrecemos colores mágicos como el efecto camaleón (que cambia de tonalidad según la posición) y el efecto holográfico (efecto arcoíris).\n\nEste modelo tiene una particularidad: un acolchado interior que camufla completamente la forma del pie para un efecto aún más realista.\n\nEl plazo de creación de este modelo es de aproximadamente 5 meses a partir de la recepción del pago, aunque esto depende del número de pedidos en curso y de la disponibilidad del material. Se le proporcionará un plazo preciso con su presupuesto gratuito.\n\nNuestras aletas \"pies invisibles en silicona\" tienen un precio a partir de 2.500 euros. Este precio corresponde a una aleta de un solo color (excluidos los efectos camaleón y holográfico), sin aletas pequeñas ni dorsal.\n\nPrecio de los detalles adicionales:\n\n- Un par de aletas laterales pequeñas, delanteras o traseras: 100 euros el par.\n\n- Aleta dorsal mediana de rodillas a tobillos: 150 euros\n\n- Aleta dorsal grande de caderas a tobillos: 200 euros\n\n- Color adicional: 50 euros por color\n\n- Color camaleón (color que cambia de tonalidad según la posición): 100 euros\n\n- Color holográfico (reflejos arcoíris): 200 euros"
  },
  "Coquillages silicone": {
    "name_en": "Silicone Shells",
    "name_es": "Conchas de silicona",
    "desc_en": "These silicone shells are available from cup A to cup C. Delivered unattached for you to sew onto your own bra — contact us to have them sewn onto a bra by us.",
    "desc_es": "Estas conchas de silicona están disponibles de la copa A a la copa C. Se entregan sueltas para que las cosa usted misma en su sujetador — contáctenos para que las cosamos en un sujetador por nuestra cuenta."
  },
  "Queue de sirène silicone \"Longfish/Extended tail\"": {
    "name_en": "Silicone Mermaid Tail \"Longfish/Extended tail\"",
    "name_es": "Cola de sirena de silicona \"Longfish/Extended tail\"",
    "desc_en": "The distinctive feature of this mermaid tail is that it has a monofin with a length extension of approximately 15 cm beyond the feet, combined with foot camouflage — creating an ultra-realistic effect that is unique in the world!\n\nThe \"Longfish\" mermaid tails are made entirely of professional-grade silicone, non-toxic for skin or aquariums. Silicone is a soft, elastic material that allows easy fitting and provides a second-skin effect. It also offers protection from the cold, like a wetsuit.\n\nWeight: approximately 10 kg.\n\n \n\nPlease note: this type of fin requires some experience compared to a standard monofin, as due to its length it is a little more difficult to handle.\n\nColours are applied beneath a layer of transparent silicone rather than airbrushed, which means the colour does not chip over time — the finish is perfect with repeated use and gives a unique iridescent effect.\n\nWe also offer magical colours such as the chameleon effect (which changes shade depending on position) and the holographic effect (rainbow effect).\n\nThe creation time for this model is approximately 6 months from receipt of payment, though this depends on the number of orders in progress and material availability. A precise lead time will be provided with your free quote.\n\nOur \"Longfish/Extended tail\" silicone fins start from 3,500 euros. This price is for a single-colour fin (excluding chameleon and holographic effects), without small fins or dorsal fins.\n\nPrice of additional options:\n\n- A pair of small lateral fins, front or back: 100 euros per pair.\n\n- Medium dorsal fin from knees to ankles: 150 euros\n\n- Large dorsal fin from hips to ankles: 200 euros\n\n- Additional colour: 50 euros per colour\n\n- Chameleon colour (colour that changes shade depending on position): 100 euros\n\n- Holographic colour (rainbow reflections): 200 euros",
    "desc_es": "La particularidad de esta cola de sirena es que posee una monoaleta con una extensión de longitud de aproximadamente 15 cm más allá de los pies, combinada con un camuflaje de los pies — ¡creando un efecto ultrarrealista y único en el mundo!\n\nLas colas de sirena \"Longfish\" están fabricadas íntegramente en silicona profesional, no tóxica para la piel ni para los acuarios. La silicona es un material suave y elástico que facilita la colocación y ofrece un efecto segunda piel. También proporciona protección contra el frío, como un traje de neopreno.\n\nPeso: aproximadamente 10 kg.\n\n \n\nAtención: este tipo de aleta requiere algo de experiencia en comparación con una monoaleta estándar, ya que debido a su longitud es algo más difícil de manejar.\n\nLos colores se aplican bajo una capa de silicona transparente en lugar de con aerógrafo, lo que evita que el color se descascare con el tiempo — el acabado es perfecto con el uso repetido y da un efecto iridiscente único.\n\nTambién ofrecemos colores mágicos como el efecto camaleón (que cambia de tonalidad según la posición) y el efecto holográfico (efecto arcoíris).\n\nEl plazo de creación de este modelo es de aproximadamente 6 meses a partir de la recepción del pago, aunque esto depende del número de pedidos en curso y de la disponibilidad del material. Se le proporcionará un plazo preciso con su presupuesto gratuito.\n\nNuestras aletas de silicona \"Longfish/Extended tail\" tienen un precio a partir de 3.500 euros. Este precio corresponde a una aleta de un solo color (excluidos los efectos camaleón y holográfico), sin aletas pequeñas ni dorsal.\n\nPrecio de los detalles adicionales:\n\n- Un par de aletas laterales pequeñas, delanteras o traseras: 100 euros el par.\n\n- Aleta dorsal mediana de rodillas a tobillos: 150 euros\n\n- Aleta dorsal grande de caderas a tobillos: 200 euros\n\n- Color adicional: 50 euros por color\n\n- Color camaleón (color que cambia de tonalidad según la posición): 100 euros\n\n- Color holográfico (reflejos arcoíris): 200 euros"
  },
  "Gants palmées silicone": {
    "name_en": "Silicone Webbed Gloves",
    "name_es": "Guantes palmeados de silicona",
    "desc_en": "Our pairs of silicone webbed gloves give you a realistic look and make swimming easier.",
    "desc_es": "Nuestros pares de guantes palmeados de silicona le ofrecen un aspecto realista y facilitan la natación."
  }
};

export default CATALOGUE_TRANSLATIONS;
