/**
 * Traductions pré-générées pour les articles du catalogue.
 * Utilisées comme source primaire avant d'appeler les services externes (Lingva, MyMemory).
 * Mettre à jour via : pnpm --filter @workspace/api-server run update-translations
 */
const CATALOGUE_TRANSLATIONS: Record<string, { name_en: string; name_es: string; desc_en: string; desc_es: string }> = {
  "Monopalme à Extension sirène": {
    "name_en": "Mermaid Extended Single Palm",
    "name_es": "Monopalma de extensión sirena",
    "desc_en": "Our monopalms have been studied for 10 years with the help of an aeronautical engineer in order to obtain perfect functionality! Unlike the monopalms on the market, which are not at all designed for mermaid swimming or to be integrated into silicone, our monopalms are fully designed for this purpose.\n\nMade of polycarbonate, a material often used in aeronautics, it offers lightness, strength and durability. Its shape has been designed to offer great maneuverability during aquatic figures while offering great speed as with a real professional diving single flipper.\n\nThey are also large, 75 to 80 cm wide by 75 cm long for all our different shapes (Siren, Ariel, Lagoon, etc.).\n\nThe lengthening between the toe of the slippers and the silicone is about 15cm, this unique feature in the world offers striking realism!\n\nThere is no water infiltration inside! The polycarbonate monopalm is completely integrated into a special silicone that sticks perfectly to the monopalm, it is this manufacturing technique that offers you a perfectly functional swim!\n\nOur slippers are very comfortable and do not cause any injury thanks to their soles! This will allow you to wear it for several hours without risk.\n\nCan be equipped with a zipper, allowing you to easily attach your fabric or silicone scales. This system also makes it possible to change the color of scales quickly and easily.\n\nWeight of the monopalm about 2 kilos.\n\nCreation time approximately 3m months.\n\nAlone, it will be equipped with silicone scales up to the toes of the slippers.\n\nFrom 1350 euros\n\n \n\nPrice of additional details:\n\n- Zipper (to attach your scales): 80 euros.\n\n-Additional colour: 20 euros per colour.\n\n-Cameleon color (color that changes shade depending on position): 75 euros\n\n-Holographic color (rainbow reflections): 100 euros.",
    "desc_es": "¡Nuestras monopalmas han sido estudiadas durante 10 años con la ayuda de un ingeniero aeronáutico para obtener una funcionalidad perfecta! A diferencia de las monopalmas del mercado, que no están diseñadas para nadar en sirena ni para integrarse en silicona, nuestras monopalmas están totalmente diseñadas para este propósito.\n\nRealizado en policarbonato, un material de uso frecuente en la aeronáutica, ofrece ligereza, resistencia y durabilidad. Su forma ha sido diseñada para ofrecer una gran maniobrabilidad durante las figuras acuáticas a la vez que ofrece una gran velocidad como con una auténtica monopalma de buceo profesional.\n\nTambién son grandes, de 75 a 80 cm de ancho por 75 cm de largo para todas nuestras diferentes formas (Siren, Ariel, Lagoon, etc.).\n\nEl alargamiento entre la punta de las zapatillas y la silicona es de unos 15 cm, ¡esta característica única en el mundo ofrece un realismo sorprendente!\n\n¡No hay infiltración de agua en el interior! La monopalma de policarbonato está completamente integrada en una silicona especial que se adhiere perfectamente a la monopalma, ¡es esta técnica de fabricación la que le ofrece una natación perfectamente funcional!\n\n¡Nuestras zapatillas son muy cómodas y no causan lesiones gracias a sus suelas! De este modo, podrás llevarla durante varias horas sin riesgos.\n\nSe pueden equipar con cremallera, lo que te permite fijar fácilmente tus escamas de tela o silicona. Este sistema también permite cambiar el color de las escamas de forma rápida y sencilla.\n\nPeso de la monopalma aproximadamente 2 kilos.\n\nPlazo de creación de unos 3 meses.\n\nSola, estará equipada con escamas de silicona hasta la punta de las zapatillas.\n\nDesde 1350 euros\n\n \n\nPrecio de los detalles adicionales:\n\n- Cremallera (para atar las escamas): 80 euros.\n\n-Color extra: 20 euros por color.\n\n-Color camaleón (color que cambia de tono según la posición): 75 euros\n\n-Color Holográfico (reflejos arco iris): 100 euros."
  },
  "Monopalme sirène": {
    "name_en": "Mermaid single palm",
    "name_es": "Monopalma sirena",
    "desc_en": "Our monopalms have been studied for 10 years with the help of an aeronautical engineer in order to obtain perfect functionality! Unlike the monopalms on the market, which are not at all designed for mermaid swimming or to be integrated into silicone, our monopalms are fully designed for this purpose.\n\nMade of polycarbonate, a material often used in aeronautics, it offers lightness, strength and durability. Its shape has been designed to offer great maneuverability during aquatic figures while offering great speed as with a real professional diving single flipper.\n\nThey are also large, 75 to 80 cm wide by 75 cm long for all our different shapes (Siren, Ariel, Lagoon, etc.).\n\nThere is no water infiltration inside! The polycarbonate monopalm is completely integrated into a special silicone that sticks perfectly to the monopalm, it is this manufacturing technique that offers you a perfectly functional swim!\n\nOur slippers are very comfortable and do not cause any injury thanks to their soles! This will allow you to wear it for several hours without risk.\n\nCan be equipped with a zipper, allowing you to easily attach your fabric or silicone scales. This system also makes it possible to change the color of scales quickly and easily.\n\nWeight of the monopalm about 2 kilos.\n\nCreation time approximately 3 months.\n\nAlone, it will be equipped with silicone scales up to the toes of the slippers.\n\nFrom 990 euros\n\n \n\nPrice of additional details:\n\n- Zipper (to attach your scales): 80 euros.\n\n-Additional colour: 20 euros per colour.\n\n-Cameleon color (color that changes shade depending on position): 75 euros\n\n-Holographic color (rainbow reflections): 100 euros.",
    "desc_es": "¡Nuestras monopalmas han sido estudiadas durante 10 años con la ayuda de un ingeniero aeronáutico para obtener una funcionalidad perfecta! A diferencia de las monopalmas del mercado, que no están diseñadas para nadar en sirena ni para integrarse en silicona, nuestras monopalmas están totalmente diseñadas para este propósito.\n\nRealizado en policarbonato, un material de uso frecuente en la aeronáutica, ofrece ligereza, resistencia y durabilidad. Su forma ha sido diseñada para ofrecer una gran maniobrabilidad durante las figuras acuáticas a la vez que ofrece una gran velocidad como con una auténtica monopalma de buceo profesional.\n\nTambién son grandes, de 75 a 80 cm de ancho por 75 cm de largo para todas nuestras diferentes formas (Siren, Ariel, Lagoon, etc.).\n\n¡No hay infiltración de agua en el interior! La monopalma de policarbonato está completamente integrada en una silicona especial que se adhiere perfectamente a la monopalma, ¡es esta técnica de fabricación la que le ofrece una natación perfectamente funcional!\n\n¡Nuestras zapatillas son muy cómodas y no causan lesiones gracias a sus suelas! De este modo, podrás llevarla durante varias horas sin riesgos.\n\nSe pueden equipar con cremallera, lo que te permite fijar fácilmente tus escamas de tela o silicona. Este sistema también permite cambiar el color de las escamas de forma rápida y sencilla.\n\nPeso de la monopalma aproximadamente 2 kilos.\n\nPlazo de creación de aproximadamente 3 meses.\n\nSola, estará equipada con escamas de silicona hasta la punta de las zapatillas.\n\nDesde 990 euros\n\n \n\nPrecio de los detalles adicionales:\n\n- Cremallera (para atar las escamas): 80 euros.\n\n-Color extra: 20 euros por color.\n\n-Color camaleón (color que cambia de tono según la posición): 75 euros\n\n-Color Holográfico (reflejos arco iris): 100 euros."
  },
  "Queue de sirène silicone": {
    "name_en": "Silicone Mermaid Tail",
    "name_es": "Cola de sirena de silicona",
    "desc_en": "Our mermaid tails are made entirely of silicone, giving them an incomparable photorealistic look! They are designed to offer a seamless, realistic finish from the waist to the tips of the fins.\n\nEach tail is custom made to the measurements of the future mermaid. Every detail counts: the color of the scales, the shape of the fins, the texture of the silicone.\n\nYou can choose your colors from our palette of more than 100 shades. The scales are sculpted by hand, one by one, for a result close to perfection.\n\nOur tails are designed to be worn with our monopalm integrated into the silicone. Swimming is fluid, powerful and spectacular.\n\nCreation time: approximately 6 to 8 months.\n\nFrom 3500 euros",
    "desc_es": "¡Nuestras colas de sirena están hechas íntegramente de silicona, lo que les da un aspecto fotorrealista incomparable! Están diseñadas para ofrecer un acabado continuo y realista desde la cintura hasta las puntas de las aletas.\n\nCada cola está fabricada a medida según las medidas de la futura sirena. Cada detalle cuenta: el color de las escamas, la forma de las aletas, la textura de la silicona.\n\nPuedes elegir tus colores de nuestra paleta de más de 100 tonos. Las escamas se esculpen a mano, una a una, para un resultado cercano a la perfección.\n\nNuestras colas están diseñadas para llevarse con nuestra monopalma integrada en la silicona. La natación es fluida, potente y espectacular.\n\nPlazo de creación: aproximadamente de 6 a 8 meses.\n\nDesde 3500 euros"
  },
  "Queue de sirène silicone \"Pieds invisibles\"": {
    "name_en": "Silicone Mermaid Tail \"Invisible Feet\"",
    "name_es": "Cola de sirena de silicona \"Pies invisibles\"",
    "desc_en": "Our \"Invisible Feet\" mermaid tails have a special feature: the slippers are completely hidden in the silicone, making the feet invisible when swimming. This gives an even more spectacular and realistic mermaid effect!\n\nLike all our tails, they are custom made to your measurements. The monopalm is fully integrated into the silicone for powerful and fluid swimming.\n\nCreation time: approximately 6 to 8 months.\n\nFrom 3800 euros",
    "desc_es": "Nuestras colas de sirena \"Pies invisibles\" tienen una característica especial: las zapatillas están completamente ocultas en la silicona, haciendo que los pies sean invisibles al nadar. ¡Esto da un efecto de sirena aún más espectacular y realista!\n\nComo todas nuestras colas, se fabrican a medida según tus medidas. La monopalma está totalmente integrada en la silicona para una natación potente y fluida.\n\nPlazo de creación: aproximadamente de 6 a 8 meses.\n\nDesde 3800 euros"
  },
  "Coquillages silicone": {
    "name_en": "Silicone shells",
    "name_es": "Conchas de silicona",
    "desc_en": "Our silicone shells are handcrafted, painted and finished by hand for a hyper-realistic look. They can be used as decoration or as a mermaid accessory.\n\nAvailable in different sizes and colors to match your mermaid tail.\n\nFrom 50 euros",
    "desc_es": "Nuestras conchas de silicona están hechas a mano, pintadas y acabadas a mano para un aspecto hiperrealista. Se pueden utilizar como decoración o como accesorio de sirena.\n\nDisponible en diferentes tamaños y colores para que coincidan con tu cola de sirena.\n\nDesde 50 euros"
  },
  "Queue de sirène silicone \"Longfish/Extended tail\"": {
    "name_en": "Silicone mermaid tail \"Longfish/Extended tail\"",
    "name_es": "Cola de sirena de silicona \"Longfish/Extended tail\"",
    "desc_en": "Our \"Longfish\" mermaid tail is our most spectacular model. With its extra-long fins extending over a meter behind the mermaid, it creates a truly extraordinary visual effect in water.\n\nThis tail is designed for experienced mermaids comfortable with swimming. The extended fins require a specific swimming technique but produce breathtaking images.\n\nCustom made to your measurements. Creation time: approximately 8 to 10 months.\n\nFrom 4500 euros",
    "desc_es": "Nuestra cola de sirena \"Longfish\" es nuestro modelo más espectacular. Con sus aletas extra largas que se extienden más de un metro detrás de la sirena, crea un efecto visual verdaderamente extraordinario en el agua.\n\nEsta cola está diseñada para sirenas experimentadas que se sientan cómodas nadando. Las aletas extendidas requieren una técnica de natación específica pero producen imágenes impresionantes.\n\nFabricada a medida según tus medidas. Plazo de creación: aproximadamente de 8 a 10 meses.\n\nDesde 4500 euros"
  },
  "Gants palmées silicone": {
    "name_en": "Silicone webbed gloves",
    "name_es": "Guantes palmeados de silicona",
    "desc_en": "Our silicone webbed gloves complete the mermaid look perfectly. Made of the same silicone as our tails, they have the same realistic scale finish.\n\nCustomizable in colors to match your mermaid tail.\n\nFrom 150 euros",
    "desc_es": "Nuestros guantes palmeados de silicona complementan perfectamente el look de sirena. Fabricados con la misma silicona que nuestras colas, tienen el mismo acabado de escamas realistas.\n\nPersonalizable en colores para que combine con tu cola de sirena.\n\nDesde 150 euros"
  }
};

export default CATALOGUE_TRANSLATIONS;
